language: python
dist: trusty
sudo: required

notifications:
  email: false

services:
  - docker

matrix:
  include:
    - python: "2.7"
      env: OS=ubuntu-14.04
    - python: "3.6"
      env: OS=ubuntu-14.04

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.6.0


before_install:
  - pwd
  - docker version
  - docker-compose version

  # Install miniconda
  - ./ci/conda_setup.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install --yes -c conda-forge python=$TRAVIS_PYTHON_VERSION distributed

  # Start containers
  - cd ./ci/sge; ./start-sge.sh; cd -
  - docker ps -a
  - docker images

install:
  - which python
  - pip install --no-deps -e .

script:
  - flake8 -j auto dask_jobqueue
  - py.test dask_jobqueue --verbose  # run tests (skip queue tests)
  - docker exec -it sge_master /bin/bash -c "cd /dask-jobqueue; pip install --no-cache-dir ."
  - docker exec -it sge_master /bin/bash -c "cd /dask-jobqueue; py.test dask_jobqueue --verbose"

after_success:
  - docker exec -it sge_master bash -c 'cat /tmp/sge*'
  - docker exec -it slave_one bash -c 'cat /tmp/exec*'
  - docker exec -it slave_two bash -c 'cat /tmp/exec*'
  # - pip install --no-cache-dir coveralls
  # - coveralls
