language: python
dist: trusty
sudo: required

notifications:
  email: false

services:
  - docker
matrix:
  include:
    - python: "2.7"
      env:
        - OS=ubuntu-14.04
        - JOBQUEUE=sge
    - python: "3.6"
      env:
        - OS=ubuntu-14.04
        - JOBQUEUE=sge
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.6.0

before_install:
  - pwd
  - docker version
  - docker-compose version
  # Install miniconda
  - ./ci/conda_setup.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install --yes -c conda-forge python=$TRAVIS_PYTHON_VERSION dask distributed flake8
  # Start jobqueue
  - source ci/${JOBQUEUE}.sh
  - jobqueue_before_install
install:
  - which python
  - pip install --no-deps -e .
  - jobqueue_install
script:
  - flake8 -j auto dask_jobqueue
  - py.test dask_jobqueue --verbose  # run tests (skip queue tests)
  - jobque_script
after_success:
  - jobqueue_after_success

  # TODO
  # - pip install --no-cache-dir coveralls
  # - coveralls
