language: python
dist: trusty
sudo: required

notifications:
  email: false

services:
  - docker
matrix:
  include:
    - python: "2.7"
      env:
        - OS=ubuntu-14.04
        - JOBQUEUE=sge
    - python: "3.6"
      env:
        - OS=ubuntu-14.04
        - JOBQUEUE=sge
    - python: "2.7"
      env:
        - OS=ubuntu-14.04
        # JOBQUEUE=none is for tests that do not need a cluster to run
        - JOBQUEUE=none
    - python: "3.6"
      env:
        - OS=ubuntu-14.04
        # JOBQUEUE=none is for tests that do not need a cluster to run
        - JOBQUEUE=none
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.6.0

before_install:
  - pwd
  # Install miniconda (only needed for basic unit tests)
  - ./ci/conda_setup.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install --yes -c conda-forge python=$TRAVIS_PYTHON_VERSION dask distributed flake8 pytest docrep
  # Start jobqueue
  - source ci/${JOBQUEUE}.sh
  - jobqueue_before_install
install:
  - which python
  - pip install --no-deps -e .
  - jobqueue_install
script:
  - flake8 -j auto dask_jobqueue
  # do not add a pytest line just here (this will fail for most JOBQUEUE env) but inside the jobqueue_script function
  - jobqueue_script
after_success:
  - jobqueue_after_success

  # TODO
  # - pip install --no-cache-dir coveralls
  # - coveralls
