language: python
dist: xenial

notifications:
  email: false

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

matrix:
  include:
#     - python: "3.6"
#       env:
#         - JOBQUEUE=sge
#     - python: "3.6"
#       env:
#         # JOBQUEUE=none is for tests that do not need a cluster to run
#         - JOBQUEUE=none
#     - python: "3.6"
#       env:
#         - JOBQUEUE=pbs
    - python: "3.6"
      env:
        - JOBQUEUE=slurm

before_install:
  - set -e
  - pwd
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - pip install docker-compose
  # Init jobqueue environment: load init and test methods
  - source ci/${JOBQUEUE}.sh
  - jobqueue_before_install
  - set +e
install:
  - set -e
  - jobqueue_install
  - set +e
script:
  - set -e
  - jobqueue_script
  - set +e
after_script:
  - jobqueue_after_script

  # TODO
  # - pip install --no-cache-dir coveralls
  # - coveralls
