language: python
dist: xenial

notifications:
  email: false

services:
  - docker
matrix:
  include:
    - python: "3.6"
      env:
        - JOBQUEUE=sge
    - python: "3.6"
      env:
        # JOBQUEUE=none is for tests that do not need a cluster to run
        - JOBQUEUE=none
    - python: "3.6"
      env:
        - JOBQUEUE=pbs
    - python: "3.6"
      env:
        - JOBQUEUE=slurm
    - python: "3.6"
      env:
        - JOBQUEUE=htcondor

before_install:
  - set -e
  - pwd
  # Init jobqueue environment: load init and test methods
  - source ci/${JOBQUEUE}.sh
  - jobqueue_before_install
  - set +e
install:
  - set -e
  - jobqueue_install
  - set +e
script:
  - set -e
  - jobqueue_script
  - set +e
after_script:
  - jobqueue_after_script

  # TODO
  # - pip install --no-cache-dir coveralls
  # - coveralls
