name: dask-jobqueue
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - flake8
  - black
  - pytest
  - pytest-asyncio
  - cryptography
  - pip:
      - git+https://github.com/dask/dask.git
      - git+https://github.com/dask/distributed.git@refs/pull/9121/head

